import 'bootstrap/dist/css/bootstrap.min.css';
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: "My First Nextjs App",
    template: "%s | my App"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
